online_store/apps/accounts/urls.py
from django.urls import path, include

from .views import RegisterUserView, LoginUserView, LogoutUserView, ProfileDetails, ProfileEdit, \
    AddAdressView, DeleteAddressView, WishlistView, OrdersView

urlpatterns = (
    path('register/', RegisterUserView.as_view(), name='register_user'),
    path('login/', LoginUserView.as_view(), name='login_user'),
    path('logout/', LogoutUserView.as_view(), name='logout_user'),
    path("profile/", include([
        path("details/<int:pk>", ProfileDetails.as_view(), name="profile_details"),
        path("edit/<int:pk>", ProfileEdit.as_view(), name="edit_profile"),
        path("add_address/", AddAdressView.as_view(), name="add_address"),
        path("delete_address/<int:pk>", DeleteAddressView.as_view(), name='delete_adress'),
        path("wishlist/", WishlistView.as_view(), name="wishlist"),
        path("orders/", OrdersView.as_view(), name="profile_orders"),
    ]))
)

online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_store.apps.frontend.urls')),
    path('', include('online_store.apps.core.urls')),
    path('', include('online_store.apps.cart.urls')),
    path('user/', include('online_store.apps.accounts.urls')),
    path('backoffice/', include('online_store.apps.backoffice.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/apps/accounts/models.py
from django.contrib.auth.hashers import make_password
from django.core.validators import MinLengthValidator
from django.db import models
from django.contrib.auth import models as auth_models

from online_store.tools.custom_validators import validate_characters_only, validate_characters_digits_only, \
    validate_numbers_plus_sign_only


class StoreUserManager(auth_models.BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The given username must be set")

        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)


class StoreUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    USERNAME_FIELD = 'email'

    objects = StoreUserManager()

    email = models.EmailField(
        null=False,
        blank=False,
        unique=True,

    )

    is_staff = models.BooleanField(
        default=False,
    )


class Profile(models.Model):
    FIRST_NAME_MAX_LENGTH = 50
    FIRST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 50
    LAST_NAME_MIN_LENGTH = 2

    user = models.OneToOneField(StoreUser, on_delete=models.CASCADE, primary_key=True)
    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(FIRST_NAME_MIN_LENGTH,
                               message=f"First name cannot have less than {FIRST_NAME_MIN_LENGTH} characters"),
            validate_characters_only,
        )
    )
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(FIRST_NAME_MIN_LENGTH,
                               message=f"Last name cannot have less than {LAST_NAME_MIN_LENGTH} characters"),
            validate_characters_only,
        )
    )
    discount_modifier = models.SmallIntegerField(default=1)

    def __str__(self):
        return f"{self.user}"


class Address(models.Model):
    COUNTRY_MAX_LENGTH = 56
    COUNTRY_MIN_LENGTH = 4

    user = models.ForeignKey(StoreUser, on_delete=models.CASCADE)
    country = models.CharField(
        max_length=COUNTRY_MAX_LENGTH,
        validators=(
            MinLengthValidator(COUNTRY_MIN_LENGTH,
                               message=f"There is no country with less than {COUNTRY_MIN_LENGTH} characters"),
            validate_characters_only,
        )
    )
    state = models.CharField(max_length=60, validators=(validate_characters_only,))
    city = models.CharField(max_length=60, validators=(validate_characters_only,))
    address = models.CharField(max_length=100, validators=(validate_characters_digits_only,))
    postal_code = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=15, validators=(validate_numbers_plus_sign_only,))
    primary = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.city} {self.address} {self.country}"

online_store/apps/accounts/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms, get_user_model
from django.utils.translation import gettext_lazy as _
from online_store.apps.accounts.models import Profile, Address

UserModel = get_user_model()


class RegisterUserForm(auth_forms.UserCreationForm):
    password2 = forms.CharField(
        label=_("Repeat Password"),
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        strip=False,
        help_text=_("Repeat password, please"),
    )

    def save(self, commit=True):
        user = super().save(commit)

        profile = Profile(
            user=user,
        )
        if commit:
            profile.save()

        return user

    class Meta(auth_forms.UserCreationForm.Meta):
        model = UserModel
        fields = ('email',)


GROUP_CHOICES = (
    ('clients', 'Clients'),
    ('staff', 'Staff'),
    ('management', 'Management'),
    ('administration', 'Administration'),
)


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ("country", "state", "city", "address", "postal_code", "phone_number")

online_store/apps/accounts/views.py
from django.contrib.auth import views as auth_views, login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied

from django.urls import reverse_lazy
from django.views import generic as views

from online_store.apps.accounts.forms import RegisterUserForm, AddAddressForm
from online_store.apps.accounts.models import Profile, Address
from online_store.apps.core.models import Wishlist
from online_store.apps.sales.models import Order

UserModel = get_user_model()


class RegisterUserView(views.CreateView):
    template_name = 'accounts/register.html'
    form_class = RegisterUserForm

    def form_valid(self, form):
        result = super().form_valid(form)
        login(self.request, self.object)
        return result

    def get_success_url(self):
        pk = self.object.pk

        return reverse_lazy('edit_profile', kwargs={'pk': pk})


class LoginUserView(auth_views.LoginView):
    template_name = 'accounts/login.html'


class LogoutUserView(auth_views.LogoutView):
    pass


class ProfileDetails(views.DetailView):
    model = Profile
    template_name = 'accounts/profile.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.pk != self.object.pk:
            raise PermissionDenied
        return context


class ProfileEdit(views.UpdateView):
    model = Profile
    template_name = 'accounts/profile_edit.html'
    fields = ('first_name', 'last_name',)

    def get_success_url(self):
        pk = self.object.pk
        return reverse_lazy('profile_details', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.pk != self.object.pk:
            raise PermissionDenied
        return context


class AddAdressView(LoginRequiredMixin, views.CreateView):
    template_name = 'accounts/add_address.html'
    form_class = AddAddressForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('profile_details', kwargs={'pk': pk})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DeleteAddressView(LoginRequiredMixin, views.DeleteView):
    template_name = 'accounts/delete_address.html'
    model = Address

    def get_success_url(self):
        pk = self.request.user.pk
        return reverse_lazy('profile_details', kwargs={'pk': pk})


class WishlistView(views.ListView):
    model = Wishlist
    template_name = 'accounts/wishlist.html'
    ordering = '-id'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class OrdersView(views.ListView):
    model = Order
    template_name = 'accounts/orders.html'
    ordering = '-id'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(customer=self.request.user)
        return queryset

templates/accounts/add_address.html
{% extends 'frontend/base.html' %}

{% block content %}
    <form class="form-control" method="post" action="{% url 'add_address' %}">
        {{ form.as_div }}
        <button type="submit" class="btn btn-primary">Save</button>
        {% csrf_token %}
    </form>

{% endblock %}

templates/accounts/delete_address.html
{% extends 'frontend/base.html' %}

{% block content %}
    <form class="form-control" method="post" action="{% url 'delete_adress' address.pk %}">
        <h3>Do you want to delete address: <br>{{ address }}</h3>

        <a href="{% url 'profile_details' pk=user.pk %}" class="btn btn-secondary">Cancel</a>

        <button type="submit" class="btn btn-danger">Delete</button>
        {% csrf_token %}
    </form>

{% endblock %}

templates/accounts/login.html
{% extends 'frontend/base.html' %}
{% block content %}
    <div class="auth">

        <form class="auth-box" id="login" action="{% url 'login_user' %}?next={{ next }}" method="post">

            {{ form }}


            <input type="hidden" value="{{ next }}" name="next"/>

            <div id="auth-btn">
                <button>Login</button>
                or
                <a href="{% url 'register_user' %}">Register</a>
            </div>

            {% csrf_token %}
        </form>
    </div>
{% endblock %}

templates/accounts/orders.html
{% extends 'frontend/base.html' %}

{% block content %}

    <div class="orderbox">
        <h4>Addresses</h4>
        <table>
            <th>Date</th>
            <th>Order ID</th>
            <th>Payment type</th>
            <th>Items</th>
            <th>Ammount</th>
            <th>Status</th>

            {% for object in object_list %}
                <tr>
                    <td>{{ object.date_ordered }}</td>
                    <td>{{ object.id }}</td>
                    <td>{{ object.payment_type }}</td>
                    <td>{{ object.get_items }}</td>
                    <td>{{ object.get_total }}</td>
                    <td>{% if object.complete %}Completed{% else %}Pending{% endif %} </td>
                </tr>
            {% empty %}
                <p>No orders yet</p>
            {% endfor %}
        </table>
    </div>

{% endblock %}

templates/accounts/profile.html
{% extends 'frontend/base.html' %}

{% block content %}

        <div class="profile">
            <h4>User details</h4>
            <div>First Name: {{ object.first_name }}</div>
            <div>Last Name: {{ object.last_name }}</div>
            <div>Email: {{ object.user.email }}</div>

            <div>
                <a href="{% url "edit_profile" pk=request.user.pk %}">
                    <button>Edit Profile</button>
                </a>
            </div>
        </div>
        <div class="addressbox">
            <h4>Addresses</h4>
            {% for address in user.address_set.all %}
                <p>{{ address }} <a href="{% url 'delete_adress' pk=address.pk %}">delete</a></p>
            {% empty %}
                <p>No shipping adresses</p>
            {% endfor %}
            <div>
                <a href="{% url "add_address" %}">
                    <button>Add new adress</button>
                </a>
            </div>
        </div>



{% endblock %}

templates/accounts/profile_edit.html
{% extends 'frontend/base.html' %}

{% block content %}
    <div class="auth">
        <form class="auth-box" action="{% url 'edit_profile' pk=user.pk %}" method="post">

            {% csrf_token %}
            {{ form }}
            <div id="auth-btn">
                <button id="profile-save" type="submit">Save</button>
            </div>
        </form>
    </div>
{% endblock %}

templates/accounts/register.html
{% extends 'frontend/base.html' %}
{% block content %}
    <div class="auth">

        <form class="auth-box" action="{% url 'register_user' %}" method="post">


            {{ form }}

            <div>
                <button>Register</button>
                or
                <a href="{% url 'login_user' %}">Login</a>

            </div>
            {% csrf_token %}
        </form>
    </div>
{% endblock %}

templates/accounts/users_list.html
{% extends 'frontend/base.html' %}
{% block content %}
    <ul>
        {% for user in object_list %}
            <li>
                {{ user }}
            </li>
        {% endfor %}

    </ul>
{% endblock %}

templates/accounts/wishlist.html
{% extends 'frontend/base.html' %}

{% block content %}
    <center><h2>Wishlist</h2></center>
    <div class="profile-wishlist">
        {% for product in object_list %}
            <div class="wish-card">
                <a href="{% url 'product_details' product.product.slug %}">
                    <img src="{{ product.product.image.url }}" width="130" height="130">
                    <div>{{ product.product.name }}</div>
                </a>
            </div>
        {% empty %}
            <p>No products in wishlist</p>
        {% endfor %}

    </div>
{% endblock %}