online_store/apps/backoffice/urls.py
from django.urls import path

from online_store.apps.backoffice.views import *

urlpatterns = (
    path('', Dashboard.as_view(), name='dashboard'),
    path('delivery/create', create_delivery_view, name='create_delivery'),
    path('delivery/view', DeliveryList.as_view(), name='view_delivery'),
    path('delivery/details/<int:delivery_id>', DeliveryDetailView.as_view(), name='details_delivery'),

    path('orders/view', OrderManagementView.as_view(), name='orders_view'),
    path('orders/process/<int:pk>', OrderProcessView.as_view(), name='order_process'),
    path('orders/edit/<int:pk>', OrderProcessView.as_view(), name='order_process'),
    path('orders/edit_item/<int:pk>', OrderItemEditView.as_view(), name='order_edit_item'),

    path('categories', CategoryManagementView.as_view(), name='category_management'),
    path('categories/edit/<int:pk>', EditCategoryView.as_view(), name='category_edit'),
    path('categories/create/', CreateCategoryView.as_view(), name='category_create'),

    path('products', ProductManagementView.as_view(), name='product_management'),
    path('products/create', CreateProductView.as_view(), name='product_create'),
    path('products/edit/<int:pk>', edit_product, name='product_edit'),
    path('products/deactivate/<int:pk>', DeactivateProductView.as_view(), name='product_deactivate'),
    path('products/delete/<int:pk>', DeleteProductView.as_view(), name='product_delete'),

    path('admin/users', UserManagement.as_view(), name='manage_users'),
    path('admin/users/edit/<int:user_pk>', UserPermissionsView.as_view(), name='user_permissions'),

)

online_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('online_store.apps.frontend.urls')),
    path('', include('online_store.apps.core.urls')),
    path('', include('online_store.apps.cart.urls')),
    path('user/', include('online_store.apps.accounts.urls')),
    path('backoffice/', include('online_store.apps.backoffice.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

online_store/apps/backoffice/models.py
from django.db import models

# Create your models here.

online_store/apps/sales/models.py
from django.contrib.auth import get_user_model
from django.db import models

from online_store.apps.core.models import Product

User = get_user_model()


class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.RESTRICT)
    date_ordered = models.DateField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    payment_type = models.CharField(max_length=30)

    def __str__(self):
        return str(self.id)

    @property
    def get_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.price for item in orderitems])
        return total

    @property
    def get_items(self):
        orderitems = self.orderitem_set.all()
        total = len(orderitems)
        return total


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.RESTRICT)
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    serial_number = models.CharField(max_length=100, unique=True, null=True)
    date_added = models.DateField(auto_now_add=True)


class ShippingDetails(models.Model):
    customer = models.ForeignKey(User, on_delete=models.RESTRICT)
    order = models.ForeignKey(Order, on_delete=models.RESTRICT)
    country = models.CharField(max_length=56)
    state = models.CharField(max_length=60)
    city = models.CharField(max_length=60)
    address = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=15)

    def __str__(self):
        return f"{self.city} {self.address} {self.country}"

online_store/apps/backoffice/forms.py
from django import forms
from django.forms import inlineformset_factory
from online_store.apps.core.models import Product, ProductAttribute, Category, CategoryAttribute
from online_store.apps.inventory.models import Inventory, Delivery
from online_store.apps.sales.models import Order


class DeliveryForm(forms.ModelForm):
    class Meta:
        model = Delivery
        fields = ['delivery_number', 'invoice_number', 'delivery_date', 'cost']
        widgets = {
            'delivery_date': forms.TextInput(attrs={'type': 'date'}),

        }


class InventoryForm(forms.ModelForm):
    class Meta:
        model = Inventory
        fields = ['product', 'product_slug', 'serial_number', 'in_stock', 'cost']

    product_id = forms.IntegerField(label='Product ID', required=False)
    product_slug = forms.CharField(required=False)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['complete', ]


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'brand', 'category', 'image', 'description', 'price', 'active']


InventoryFormSet = forms.modelformset_factory(Inventory, form=InventoryForm, extra=1)

ProductAttributeFormSet = inlineformset_factory(
    Product,
    ProductAttribute,
    fields=('name', 'value',),
    extra=0,
    can_delete=False,
    labels={'name': '', 'value': ''}
)

CategoryAttributeFormSet = inlineformset_factory(
    Category,
    CategoryAttribute,
    fields=('name',),
    extra=0,
)

online_store/apps/backoffice/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import Group

from django.views import generic as views

from online_store.tools.access_control import AccessRequiredMixin, group_required
from online_store.apps.backoffice.forms import *
from online_store.apps.core.models import Product, Category
from online_store.apps.inventory.models import Delivery, Inventory
from online_store.apps.sales.models import Order, OrderItem

UserModel = get_user_model()


class Dashboard(AccessRequiredMixin, views.TemplateView):
    REQUIRED_GROUP = "Staff"
    template_name = 'backoffice/dashboard.html'


class CreateDelivery(AccessRequiredMixin, views.CreateView):
    REQUIRED_GROUP = "Staff"
    model = Delivery
    template_name = 'backoffice/delivery/create_delivery.html'
    success_url = reverse_lazy('dashboard')
    fields = '__all__'


@group_required("Staff")
def create_delivery_view(request):
    if request.method == 'POST':
        delivery_form = DeliveryForm(request.POST)
        forms_count = sum(1 for key in request.POST if key.startswith('form-')) / 5
        inventory_forms = [InventoryForm(request.POST, prefix=f'form-{i}') for i in range(int(forms_count))]

        if delivery_form.is_valid() and all(form.is_valid() for form in inventory_forms):
            if delivery_form.cleaned_data['cost'] != sum(form.cleaned_data['cost'] for form in inventory_forms):
                raise ValidationError("The total delivery amount is different from the sum of items cost")
            delivery = Delivery.objects.create(
                delivery_number=delivery_form.cleaned_data['delivery_number'],
                invoice_number=delivery_form.cleaned_data['invoice_number'],
                delivery_date=delivery_form.cleaned_data['delivery_date'],
                cost=delivery_form.cleaned_data['cost'],
                created_by=request.user
            )

            for form in inventory_forms:
                inventory = form.save(commit=False)

                product_slug = form.cleaned_data['product_slug']
                try:
                    product = Product.objects.get(slug=product_slug)
                    inventory.product = product
                    inventory.delivery = delivery
                    inventory.in_stock = True
                    inventory.save()
                except Product.DoesNotExist:
                    raise ValidationError('Product does not exist')

            return redirect('dashboard')
    else:
        delivery_form = DeliveryForm()
        inventory_forms = [InventoryForm(prefix=f'form-{i}') for i in range(1)]

    return render(request, 'backoffice/delivery/create_delivery.html', {
        'delivery_form': delivery_form,
        'inventory_forms': inventory_forms,
    })


class DeliveryList(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Staff"
    model = Delivery
    template_name = 'backoffice/delivery/delivery_list.html'
    context_object_name = 'objects_list'


class DeliveryDetailView(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Staff"
    model = Inventory
    template_name = 'backoffice/delivery/delivery_details.html'
    context_object_name = 'objects_list'

    def get_queryset(self):
        queryset = super().get_queryset()
        delivery_id = self.kwargs['delivery_id']
        return queryset.filter(delivery_id=delivery_id)


class UserManagement(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Admins"
    model = UserModel
    template_name = 'backoffice/user/user_management.html'


class UserPermissionsView(AccessRequiredMixin, views.View):
    REQUIRED_GROUP = "Admins"
    template_name = 'backoffice/user/user_permissions.html'

    def get(self, request, user_pk):
        user = get_object_or_404(UserModel, pk=user_pk)
        groups = Group.objects.all()
        return render(request, self.template_name, {'user': user, 'groups': groups})

    def post(self, request, user_pk):
        user = get_object_or_404(UserModel, pk=user_pk)
        groups = Group.objects.all()
        for group in groups:
            is_checked = request.POST.get(group.name, False)
            if is_checked:
                user.groups.add(group)
            else:
                user.groups.remove(group)
        return redirect('manage_users')


class CategoryManagementView(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Managers"
    model = Category
    template_name = 'backoffice/category/category_management.html'


class CreateCategoryView(AccessRequiredMixin, views.CreateView):
    REQUIRED_GROUP = "Managers"
    model = Category
    fields = ('name', 'parent_category', 'order',)
    template_name = 'backoffice/category/category_create.html'
    success_url = reverse_lazy('category_management')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['attribute_formset'] = CategoryAttributeFormSet(self.request.POST)
        else:
            context['attribute_formset'] = CategoryAttributeFormSet()
        return context

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        categories = Category.objects.filter(parent_category=None)
        form.fields['parent_category'].queryset = categories
        return form

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        context = self.get_context_data()
        attribute_formset = context['attribute_formset']
        category = form.save()
        if attribute_formset.is_valid():
            for form in attribute_formset:
                a = form
                if form.cleaned_data.get('name'):
                    attribute = form.save(commit=False)
                    attribute.category = category
                    attribute.save()
            return super().form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class EditCategoryView(AccessRequiredMixin, views.UpdateView):
    REQUIRED_GROUP = "Managers"
    model = Category
    fields = ('name', 'parent_category', 'order',)
    template_name = 'backoffice/category/category_edit.html'
    success_url = reverse_lazy('category_management')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        categories = Category.objects.filter(parent_category=None)
        categories.exclude(pk=self.object.pk)
        form.fields['parent_category'].queryset = categories
        return form


class ProductManagementView(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Staff"
    model = Product
    template_name = 'backoffice/product/product_management.html'
    paginate_by = 15
    ordering = ['pk']


class CreateProductView(AccessRequiredMixin, views.CreateView):
    REQUIRED_GROUP = "Staff"
    model = Product
    fields = '__all__'
    template_name = 'backoffice/product/product_create.html'


class DeactivateProductView(AccessRequiredMixin, views.UpdateView):
    REQUIRED_GROUP = "Staff"
    model = Product
    fields = []
    template_name = 'backoffice/product/product_deactivate.html'
    success_url = reverse_lazy('product_management')

    def form_valid(self, form):
        self.object.active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@login_required
@group_required("Staff")
def edit_product(request, pk):
    product = Product.objects.get(pk=pk)

    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        formset = ProductAttributeFormSet(request.POST, instance=product)
        if form.is_valid() and formset.is_valid():
            formset.save()
            form.save()
            return redirect('product_management')

    else:
        form = ProductForm(instance=product)
        formset = ProductAttributeFormSet(instance=product)

    context = {
        'product': product,
        'form': form,
        'formset': formset,
    }
    return render(request, 'backoffice/product/product_edit.html', context)


class DeleteProductView(AccessRequiredMixin, views.DeleteView):
    REQUIRED_GROUP = "Managers"
    model = Product
    template_name = 'backoffice/product/product_delete.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        has_items = Inventory.objects.filter(product=self.object).exists()
        context.update({'has_items': has_items})
        return context


class OrderManagementView(AccessRequiredMixin, views.ListView):
    REQUIRED_GROUP = "Staff"
    model = Order
    template_name = 'backoffice/order/order_management.html'


class OrderProcessView(AccessRequiredMixin, views.UpdateView):
    REQUIRED_GROUP = "Staff"
    model = Order
    template_name = 'backoffice/order/order_process.html'
    form_class = OrderForm
    success_url = reverse_lazy('orders_view')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        order_items = OrderItem.objects.filter(order=self.object)
        context.update({'order_items': order_items})
        return context


class OrderItemEditView(AccessRequiredMixin, views.UpdateView):
    REQUIRED_GROUP = "Staff"
    model = OrderItem
    template_name = 'backoffice/order/orderitem_edit.html'
    fields = ['serial_number']

    def get_success_url(self):
        order = self.object.order
        return reverse('order_process', kwargs={"pk": order.pk})

    def form_valid(self, form):
        old_serial = self.get_object().serial_number
        new_serial = form.cleaned_data["serial_number"]

templates/backoffice/order/order_management.html
{% extends 'backoffice/base.html' %}

{% block extrahead %}
    <style>
        .cart-row {
            display: flex;
            align-items: stretch;
            padding-bottom: 5px;
            margin-bottom: 5px;
            border-bottom: 1px solid #ececec;

        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock %}



{% block content %}
    <h2>Orders:</h2>
    <input type="text" id="searchInput" placeholder="Search">
    <table>

        <div class="cart-row">
            <div style="flex:1"><strong>ORDER ID</strong></div>
            <div style="flex:2"><strong>ORDER DATE</strong></div>
            <div style="flex:1"><strong>COMPLETED</strong></div>
            <div style="flex:1"><strong>PAYMENT_TYPE</strong></div>
            <div style="flex:1"><strong>AMMOUNT</strong></div>
            <div style="flex:1"><strong>ACTION</strong></div>
        </div>
        {% for order in object_list %}
            <div class="cart-row user-row">
                <div style="flex:1"><p>{{ order.id }}</p></div>
                <div style="flex:2"><p>{{ order.date_ordered }}</p></div>
                <div style="flex:1"><p>{{ order.complete }}</p></div>
                <div style="flex:1"><p>{{ order.payment_type }}</p></div>
                <div style="flex:1"><p>{{ order.get_total }}</p></div>
                <div style="flex:1"><p><a href="{%  url 'order_process' pk=order.pk %}">process</a></p></div>

            </div>
        {% empty %}
            <h3>No orders</h3>
        {% endfor %}
    </table>

    <script>
        $(document).ready(function () {
            $("#searchInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $(".user-row").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

templates/backoffice/order/order_process.html
{% extends 'backoffice/base.html' %}

{% block extrahead %}
    <style>
        .cart-row {
            display: flex;
            align-items: stretch;
            padding-bottom: 5px;
            margin-bottom: 5px;
            border-bottom: 1px solid #ececec;

        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% endblock %}



{% block content %}


    <h2>Order: {{ order.pk }}</h2>
    <div>Client: {{ order.customer.profile.first_name }} {{ order.customer.profile.last_name }}</div>
    <div>Client email: {{ order.customer }} </div>
    <div>Delivery Address: {{ order.shippingdetails_set.get }}</div>
    <br>
    <table>

        <div class="cart-row">
            <div style="flex:1"><strong>PRODUCT ID</strong></div>
            <div style="flex:1"><strong>PRODUCT</strong></div>
            <div style="flex:1"><strong>SERIAL NUMBER</strong></div>
            <div style="flex:1"><strong>PRICE</strong></div>
            <div style="flex:1"><strong>ACTION</strong></div>
        </div>
        {% for item in order_items %}
            <div class="cart-row user-row">
                <div style="flex:1"><p>{{ item.product.id }}</p></div>
                <div style="flex:1"><p>{{ item.product.slug }}</p></div>
                <div style="flex:1">{{ item.serial_number }}</div>
                <div style="flex:1"><p>{{ item.price }}</p></div>
                <div style="flex:1">
                    <a href="{% url 'order_edit_item' pk=item.pk %}">edit</a>
                </div>
            </div>
        {% empty %}
            <h3>No users</h3>
        {% endfor %}
    </table>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save</button>
    </form>

    <script>
        $(document).ready(function () {
            $("#searchInput").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $(".user-row").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
    </script>
{% endblock %}

templates/backoffice/order/orderitem_edit.html
{% extends 'backoffice/base.html' %}

{% block content %}
    <h2>Edit Order Item: {{ object.product.slug }}</h2>
    <form method="post">
        {% csrf_token %}
        <p>Old serial number: {{ object.serial_number }}</p>
        <p>New serial number:{{ form.serial_number }}</p>
        <button type="submit">Save</button>
    </form>
{% endblock %}